server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: docker
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
