version: '3'

services:
  config-server:
    image: bowan.azurecr.io/spring-petclinic-config-server
    container_name: config-server
    mem_limit: 512M
    ports:
     - 8888:8888

  discovery-server:
    image: bowan.azurecr.io/spring-petclinic-discovery-server
    container_name: discovery-server
    mem_limit: 512M
    restart: on-failure
    depends_on:
      - config-server
    entrypoint: ["java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8761:8761

  customers-service:
    image: bowan.azurecr.io/spring-petclinic-customers-service
    container_name: customers-service
    mem_limit: 512M
    restart: on-failure
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["java", "org.springframework.boot.loader.JarLauncher"]
    ports:
    - 8081:8081

  visits-service:
    image: bowan.azurecr.io/spring-petclinic-visits-service
    container_name: visits-service
    mem_limit: 512M
    restart: on-failure
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8082:8082

  vets-service:
    image: bowan.azurecr.io/spring-petclinic-vets-service
    container_name: vets-service
    mem_limit: 512M
    restart: on-failure
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8083:8083

  api-gateway:
    image: bowan.azurecr.io/spring-petclinic-api-gateway
    container_name: api-gateway
    mem_limit: 512M
    restart: on-failure
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8080:8080

  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    mem_limit: 512M
    environment:
    - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    ports:
     - 9411:9411

  admin-server:
    image: bowan.azurecr.io/spring-petclinic-admin-server
    container_name: admin-server
    mem_limit: 512M
    restart: on-failure
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 9090:9090

  ## Grafana / Prometheus

  # grafana-server:
  #   build: ./docker/grafana
  #   container_name: grafana-server
  #   mem_limit: 256M
  #   ports:
  #   - 3000:3000

  # prometheus-server:
  #   build: ./docker/prometheus
  #   container_name: prometheus-server
  #   mem_limit: 256M
  #   ports:
  #   - 9091:9090
