apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - image: bowan.azurecr.io/spring-petclinic-api-gateway:latest
          name: api-gateway
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8080
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: spring-petclinic
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-ipv4: "20.237.100.158"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: api-gateway
