apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: visits-service
  name: visits-service
  namespace: spring-petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
        - image: bowan.azurecr.io/spring-petclinic-visits-service:latest
          name: visits-service
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi
          ports:
            - containerPort: 8082
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
  namespace: spring-petclinic
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    app: visits-service
